services:
  app_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app_backend:latest
    container_name: app_backend
    ports:
      - "9000:8081"
    networks:
      - backend-network

  database:
    env_file:
      - .env
    image: postgres:latest
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: freelance-erp
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db:/var/lib/postgresql/data/
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./pgadmin:/var/lib/pgadmin/
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge