services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: erp-freelance-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - erp-freelance-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    container_name: erp-freelance-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${URL_POSTGRES}
      SPRING_DATASOURCE_USERNAME: ${USER_ERP_FREELANCE}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD_POSTGRESQL}
    networks:
      - erp-freelance-network

networks:
  erp-freelance-network:
    name: erp-freelance-network
    driver: bridge
