services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: erp-freelance-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - erp-freelance-network:
    depends_on:
      backend:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: erp-freelance-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_URL}:5432/prospection
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - erp-freelance-network:

networks:
  erp-freelance-network:
    name: erp-freelance-network
    driver: bridge  
